### ISSUE TITLE
Tests fail after new version of structcol installed

### ISSUE THREAD

**Issue by vnmanoharan** [p201-sp2016/infer_structcol#25]
I merged the three latest pull requests into structcol, then cloned the repo and copied the package into infer-structcol, but now a couple of tests fail with ValueErrors (note also the warning about divide by zero):

```
infer_structcol.tests.test_io.test_io ... ok
infer_structcol.tests.test_main.test_Spectrum ... ok
infer_structcol.tests.test_main.test_Sample ... ok
infer_structcol.tests.test_main.test_extend_array ... ok
infer_structcol.tests.test_main.test_rescale ... ok
infer_structcol.tests.test_main.test_find_close_indices ... ok
infer_structcol.tests.test_model.test_prior ... ok
infer_structcol.tests.test_model.test_likelihood ... ok
infer_structcol.tests.test_model.test_log_posterior ... C:\Users\vnm\Anaconda3\lib\site-packages\pint\quantity.py:761: RuntimeWarning: divide by zero encountered in double_scalars
  return self.__class__(other_magnitude / self._magnitude, 1 / self._units)
ERROR
infer_structcol.tests.test_run_structcol.test_structcol_import ... ok
infer_structcol.tests.test_run_structcol.test_run_structcol ... ERROR
structcol.tests.test_mie.test_cross_sections ... ok
structcol.tests.test_mie.test_form_factor ... ok
structcol.tests.test_mie.test_efficiencies ... ok
structcol.tests.test_mie.test_absorbing_materials ... ok
structcol.tests.test_model.test_fresnel ... ok
structcol.tests.test_montecarlo.test_sampling ... C:\Users\vnm\Anaconda3\lib\site-packages\pint\quantity.py:761: RuntimeWarning: divide by zero encountered in double_scalars
  return self.__class__(other_magnitude / self._magnitude, 1 / self._units)
ok
structcol.tests.test_montecarlo.test_fresnel_refl ... ok
structcol.tests.test_montecarlo.test_calc_reflection ... ok
structcol.tests.test_montecarlo.test_trajectories ... ok
structcol.tests.test_refractive_index.test_n ... ok
structcol.tests.test_refractive_index.test_water ... ok
structcol.tests.test_refractive_index.test_npmma ... ok
structcol.tests.test_refractive_index.test_nps ... ok
structcol.tests.test_refractive_index.test_rutile ... ok
structcol.tests.test_refractive_index.test_fused_silica ... ok
structcol.tests.test_refractive_index.test_vacuum ... ok
structcol.tests.test_structcol.test_q ... ok
structcol.tests.test_structure.test_structure_factor_percus_yevick ... ok

======================================================================
ERROR: infer_structcol.tests.test_model.test_log_posterior
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\vnm\Anaconda3\lib\site-packages\nose\case.py", line 198, in runTest
    self.test(*self.arg)
  File "C:\Users\vnm\Documents\GitHub\p201\infer_structcol\infer_structcol\tests\test_model.py", line 29, in test_log_posterior
    post = log_posterior(theta, spectrum, sample, 0.5, seed=2)
  File "C:\Users\vnm\Documents\GitHub\p201\infer_structcol\infer_structcol\model.py", line 78, in log_posterior
    theory_spectrum = calc_reflectance(vol_frac, sample, seed=seed)
  File "C:\Users\vnm\Documents\GitHub\p201\infer_structcol\infer_structcol\run_structcol.py", line 86, in calc_reflectance
    R_fraction = mc.calc_reflection(r[2], sc.Quantity('0.0 um'), thickness, ntrajectories, matrix_index[i], sample_index[i], k[0], k[1], k[2], detection_angle=np.pi/2)
  File "C:\Users\vnm\Documents\GitHub\p201\infer_structcol\structcol\montecarlo.py", line 404, in calc_reflection
    if not refl_row_indices:
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

======================================================================
ERROR: infer_structcol.tests.test_run_structcol.test_run_structcol
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\vnm\Anaconda3\lib\site-packages\nose\case.py", line 198, in runTest
    self.test(*self.arg)
  File "C:\Users\vnm\Documents\GitHub\p201\infer_structcol\infer_structcol\tests\test_run_structcol.py", line 28, in test_run_structcol
    incident_angle), seed=1)
  File "C:\Users\vnm\Documents\GitHub\p201\infer_structcol\infer_structcol\run_structcol.py", line 86, in calc_reflectance
    R_fraction = mc.calc_reflection(r[2], sc.Quantity('0.0 um'), thickness, ntrajectories, matrix_index[i], sample_index[i], k[0], k[1], k[2], detection_angle=np.pi/2)
  File "C:\Users\vnm\Documents\GitHub\p201\infer_structcol\structcol\montecarlo.py", line 404, in calc_reflection
    if not refl_row_indices:
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

----------------------------------------------------------------------
Ran 29 tests in 4.327s

FAILED (errors=2)
```

**Comment by victoriahwang89** [comment]
Fixed a bug in structcol/montecarlo.py. The tests now pass.
