### ISSUE TITLE
Tests fail

### ISSUE THREAD

**Issue by vnmanoharan** [p201-sp2016/infer_structcol#31]
Running `nosetests -v` in the root directory gives the following output:
```
infer_structcol.tests.test_inference.test_calc_max_like ... ok
infer_structcol.tests.test_inference.test_run_mcmc ... C:\Users\vnm\Anaconda3\lib\site-packages\emcee\ensemble.py:335: RuntimeWarning: invalid value encountered in subtract
  lnpdiff = (self.dim - 1.) * np.log(zz) + newlnprob - lnprob0
C:\Users\vnm\Anaconda3\lib\site-packages\emcee\ensemble.py:336: RuntimeWarning: invalid value encountered in greater
  accept = (lnpdiff > np.log(self._random.rand(len(lnpdiff))))
ok
infer_structcol.tests.test_io.test_io ... ok
infer_structcol.tests.test_main.test_Spectrum ... ok
infer_structcol.tests.test_main.test_Sample ... ok
infer_structcol.tests.test_main.test_extend_array ... ok
infer_structcol.tests.test_main.test_rescale ... ok
infer_structcol.tests.test_main.test_find_close_indices ... ok
infer_structcol.tests.test_main.test_check_wavelength ... ok
infer_structcol.tests.test_model.test_calc_model_spect ... FAIL
infer_structcol.tests.test_model.test_calc_resid_spect ... ok
infer_structcol.tests.test_model.test_prior ... ok
infer_structcol.tests.test_model.test_likelihood ... ok
infer_structcol.tests.test_model.test_log_posterior ... ok
infer_structcol.tests.test_run_structcol.test_structcol_import ... ok
infer_structcol.tests.test_run_structcol.test_run_structcol ... ok
structcol.tests.test_mie.test_cross_sections ... ok
structcol.tests.test_mie.test_form_factor ... ok
structcol.tests.test_mie.test_efficiencies ... ok
structcol.tests.test_mie.test_absorbing_materials ... ok
structcol.tests.test_model.test_fresnel ... ok
structcol.tests.test_montecarlo.test_sampling ... ok
structcol.tests.test_montecarlo.test_fresnel_refl ... ok
structcol.tests.test_montecarlo.test_trajectory_status ... ok
structcol.tests.test_montecarlo.test_calc_reflection ... ok
structcol.tests.test_montecarlo.test_trajectories ... ok
structcol.tests.test_refractive_index.test_n ... ok
structcol.tests.test_refractive_index.test_water ... ok
structcol.tests.test_refractive_index.test_npmma ... ok
structcol.tests.test_refractive_index.test_nps ... ok
structcol.tests.test_refractive_index.test_rutile ... ok
structcol.tests.test_refractive_index.test_fused_silica ... ok
structcol.tests.test_refractive_index.test_vacuum ... ok
structcol.tests.test_structcol.test_q ... ok
structcol.tests.test_structure.test_structure_factor_percus_yevick ... ok

======================================================================
FAIL: infer_structcol.tests.test_model.test_calc_model_spect
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\vnm\Anaconda3\lib\site-packages\nose\case.py", line 198, in runTest
    self.test(*self.arg)
  File "C:\Users\vnm\Documents\GitHub\p201\infer_structcol\infer_structcol\tests\test_model.py", line 10, in test_calc_model_spect
    assert_frame_equal(calc_model_spect(sample, theta, 2), Spectrum(500, 0.507608289932, 0.0261746352879))
  File "C:\Users\vnm\Anaconda3\lib\site-packages\pandas\util\testing.py", line 1313, in assert_frame_equal
    obj='DataFrame.iloc[:, {0}]'.format(i))
  File "C:\Users\vnm\Anaconda3\lib\site-packages\pandas\util\testing.py", line 1154, in assert_series_equal
    assert_attr_equal('dtype', left, right)
  File "C:\Users\vnm\Anaconda3\lib\site-packages\pandas\util\testing.py", line 878, in assert_attr_equal
    left_attr, right_attr)
  File "C:\Users\vnm\Anaconda3\lib\site-packages\pandas\util\testing.py", line 1018, in raise_assert_detail
    raise AssertionError(msg)
AssertionError: Attributes are different

Attribute "dtype" are different
[left]:  int32
[right]: int64

----------------------------------------------------------------------
Ran 35 tests in 4.551s
```

**Comment by vnmanoharan** [comment]
I should note that this is with the latest version of structcol, with the pull request that @barkls submitted today.  Didn't try with the previous version.

**Comment by barkls** [comment]
I wasn't able to reproduce these failing tests. I've pushed some code that will hopefully maintain consistent dtypes and avoid the problem. It would be great if you can try the tests again and close this issue if it is fixed.

Thanks!

**Comment by vnmanoharan** [comment]
Tests now pass.
