### ISSUE TITLE
test failure

### ISSUE THREAD

**Issue by vnmanoharan** [p201-sp2016/infer_structcol#36]
I'm getting a test failure when I use the latest revision of structcol (didn't test it with the previous version):
```
======================================================================
FAIL: infer_structcol.tests.test_io.test_io
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\vnm\Anaconda3\lib\site-packages\nose\case.py", line 198, in runTest
    self.test(*self.arg)
  File "C:\Users\vnm\Documents\GitHub\p201\infer_structcol\infer_structcol\tests\test_io.py", line 20, in test_io
    assert_almost_equal(spectrum.reflectance[0],0.41846705358309988)
  File "C:\Users\vnm\Anaconda3\lib\site-packages\numpy\testing\utils.py", line 539, in assert_almost_equal
    raise AssertionError(_build_err_msg())
AssertionError:
Arrays are not almost equal to 7 decimals
 ACTUAL: 0.41925014900339536
 DESIRED: 0.4184670535830999

----------------------------------------------------------------------
Ran 35 tests in 4.667s
```

**Comment by AnnieStephenson** [comment]
This is due to an update in the test data. There was some lag time between updating the test data and updating the tests, but this has been fixed now, and the tests should run without error.
